<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <!--
        El proyecto Web no necesita referencias directas a EF Core, Npgsql o Identity.
        Su única responsabilidad es la presentación. Obtiene los servicios que necesita
        a través de las referencias a los proyectos de Application e Infrastructure.
      -->
      <PackageReference Include="EPPlus" Version="7.1.2" />
      <PackageReference Include="QuestPDF" Version="2023.12.6" />
    </ItemGroup>

    <ItemGroup>
      <!--
        Se añaden las referencias a los proyectos de las capas inferiores para poder
        inyectar y utilizar sus servicios.
      -->
      <ProjectReference Include="..\Firmeza.Application\Firmeza.Application.csproj" />
      <ProjectReference Include="..\Firmeza.Infrastructure\Firmeza.Infrastructure.csproj" />
    </ItemGroup>

</Project>
